# Populate Citys table
#USE Metal;
#SELECT MAX(char_length(city) - char_length(replace(city, ',',''))) FROM Staging;


INSERT IGNORE INTO City (cityName)
WITH CTE AS (
SELECT REPLACE(city, ';', ',') AS city
FROM (
	SELECT REPLACE(city, '/', ',') AS city
    FROM (
	SELECT
	(CASE
	WHEN city LIKE '%(%)%'
	THEN CONCAT(
		TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, '(', 1), ')', -1)),
	    TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, '(', 2), ')', -1)),
	    TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, '(', 3), ')', -1)),
	    TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, '(', 4), ')', -1)),
	    TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, '(', 5), ')', -1))
	    )
	ELSE city
	END) AS city
	FROM Staging

        WHERE city <> 'N/A' AND city IS NOT NULL
    ) AS E1
) AS E
)
SELECT DISTINCT(
CASE
WHEN CHAR_LENGTH(city) - CHAR_LENGTH(REPLACE(city, ',', '')) > 0
THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, ',', 2), ',', -1))
END) AS city
FROM CTE UNION
SELECT DISTINCT(
CASE
WHEN CHAR_LENGTH(city) - CHAR_LENGTH(REPLACE(city, ',', '')) > 1
THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, ',', 3), ',', -1))
END)
FROM CTE UNION
SELECT DISTINCT(
CASE
WHEN CHAR_LENGTH(city) - CHAR_LENGTH(REPLACE(city, ',', '')) > 2
THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, ',', 4), ',', -1))
END)
FROM CTE UNION
SELECT DISTINCT(
CASE
WHEN CHAR_LENGTH(city) - CHAR_LENGTH(REPLACE(city, ',', '')) > 3
THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, ',', 5), ',', -1))
END)
FROM CTE UNION
SELECT DISTINCT(
CASE
WHEN CHAR_LENGTH(city) - CHAR_LENGTH(REPLACE(city, ',', '')) > 4
THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, ',', 6), ',', -1))
END)
FROM CTE UNION
SELECT DISTINCT(
CASE
WHEN CHAR_LENGTH(city) - CHAR_LENGTH(REPLACE(city, ',', '')) > 5
THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, ',', 7), ',', -1))
END)
FROM CTE UNION
SELECT DISTINCT(
CASE
WHEN CHAR_LENGTH(city) - CHAR_LENGTH(REPLACE(city, ',', '')) > 6
THEN TRIM(SUBSTRING_INDEX(SUBSTRING_INDEX(city, ',', 8), ',', -1))
END)
FROM CTE;



